version: "3.9"
services:
  grafana:
    image: grafana/grafana:9.3.0
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafana-data:/var/lib/grafana:rw
    environment:
      - GF_DATABASE_HOST=grafana_db:3306
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=nathan
      - GF_DATABASE_PASSWORD=nathan123
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on: ["grafana_db"]
  grafana_db:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: rootnih
      MYSQL_DATABASE: grafana
      MYSQL_USER: nathan
      MYSQL_PASSWORD: nathan123
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
        --innodb_monitor_enable=all,
        --max-connections=1001,
      ]
    ports:
      - 3306:3006
    networks:
      - monitoring
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

volumes:
  grafana-data:
    name: grafana-data
    external: true
  mysql-data:
    name: mysql-data
    external: true


networks:
    monitoring:
        external: true